# Generated by Django 3.0.2 on 2025-04-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childApp', '0002_auto_20250409_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childmodel',
            name='Mood',
        ),
        migrations.AddField(
            model_name='childmodel',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
