# Generated by Django 3.0.2 on 2025-04-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childmodel',
            old_name='Packed_cell_volume',
            new_name='Meals_Per_Day',
        ),
        migrations.RenameField(
            model_name='childmodel',
            old_name='Blood_Urea',
            new_name='Screen_Time',
        ),
        migrations.RenameField(
            model_name='childmodel',
            old_name='White_blood_count',
            new_name='Sleep_Hours',
        ),
        migrations.RenameField(
            model_name='childmodel',
            old_name='Serum_Creatine',
            new_name='Study_Hours',
        ),
        migrations.RemoveField(
            model_name='childmodel',
            name='Blood_Glucose_Random',
        ),
        migrations.AddField(
            model_name='childmodel',
            name='Mood',
            field=models.CharField(default='Happy', max_length=40),
        ),
    ]
